/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './deal-with-it.module';
import * as i2 from '@angular/common';
import * as i3 from './deal-with-it.service';
export const DealWithItModuleNgFactory:i0.NgModuleFactory<i1.DealWithItModule> = i0.ɵcmf(i1.DealWithItModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,
          i2.NgLocalization,i2.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(4608,i3.DealWithItService,
          i3.DealWithItService,([] as any[])),i0.ɵmpd(512,i2.CommonModule,i2.CommonModule,
          ([] as any[])),i0.ɵmpd(512,i1.DealWithItModule,i1.DealWithItModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL09yRGUvRGV2ZWxvcG1lbnQvbmcyLWRlYWx3aXRoaXQvc3JjL2RlYWwtd2l0aC1pdC5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvT3JEZS9EZXZlbG9wbWVudC9uZzItZGVhbHdpdGhpdC9zcmMvZGVhbC13aXRoLWl0Lm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
